/**
 * Voiceover prompt blocks. They are added to the role instructions only when the runtime has a voice host (the beta
 * flag): without it the agents are told nothing about narration, so they never promise what they cannot do.
 */

const VOICE_SETUP_RULES = `The voice comes from the user's own provider account (Gemini, OpenAI, OpenRouter, ElevenLabs or a server they run); you never see a key and never choose a provider or an address. request_voice_setup {language, sampleText, suggestion} asks the user to pick the voice in the chat and waits: it returns the chosen voice and its script dialect (the tags, pauses, style field and length limits the script must follow). If the user declines or does not answer, there is no voiceover: say so and stop, never look for another way to make speech.`;

const VOICE_SCRIPT_RULES = `Script: one line per sentence or short beat (a line is also what a caption and a timeline clip stand for). Every line has text (what the viewer reads) and speakerText (what the narrator reads: the dialect's tags, pauses and emphasis, numbers written out as words where the dialect says so); style only where the dialect has a style field. Write the script in the dialect request_voice_setup returned — a tag of another model's syntax is read aloud or refused. Keep each line's id when you revise a line that was already generated, so its takes and clips stay attached.`;

/** What the Director adds to its own instructions when the runtime has a voice host. */
export const VOICE_DIRECTOR = `Voiceover: when the user asks for narration, a voiceover or a spoken script, call request_voice_setup FIRST (language of the script, sampleText = its first sentence, suggestion = the character you think fits) and wait for the user's choice — never write the script or generate speech before a voice is chosen. ${VOICE_SETUP_RULES}
Then write the script in the returned dialect. ${VOICE_SCRIPT_RULES} When the script is long or the user may want to change it before money is spent, show it with propose_plan when the turn offers it: one step per line, the step title being the line's speaker text — the chat renders its tags as chips; a plan holds at most 12 steps of 120 characters, so for a longer script group the lines of one beat into a step and cut long sentences into short ones. Then hand the generation to Audio when it is enabled: delegate with a self-contained task that carries the final script (every line's text, speakerText, style and id), the chosen voice's dialect rules and where the narration goes on the timeline. When Audio is off you have generate_voiceover yourself and follow the Audio working rules below. Generation costs money on the user's account: generate_voiceover asks them first, plays the first line as a pilot and continues only after they press Continue — never generate the same lines twice to "try again", and when the user asks for changes after the pilot, change the script and call again.`;

/** The Audio specialist's voiceover duties, and what the Director follows for it when Audio is off. */
export const VOICE_AUDIO = `Voiceover: when your task asks for narration, work in this order. (1) If the task does not already carry the chosen voice and its dialect, call request_voice_setup {language, sampleText, suggestion}. ${VOICE_SETUP_RULES} (2) ${VOICE_SCRIPT_RULES} (3) Call generate_voiceover {lines, lineIds?}: it saves the script, checks it against the dialect (problems come back to you before anything is paid — fix every one and call again), asks the user to allow the cost, generates the first line as a pilot for the user to hear and, after they press Continue, the rest in the same call. When the user asks for changes you get their note back: change the script (speakerText, style, wording) and call again; lines whose text did not change keep their takes and cost nothing. Server problems come back as text — a rejected key, a rate limit with its retry time, an exhausted quota, an answer that is not audio: report them in your result and do not retry in a loop. (4) Place every generated line with edit_timeline add_clip {voiceLine: "<line id>", start, track}: the clip takes the file, the range and the length of the line's selected take, joins the "voiceover" audio group and stays linked to the line; put the narration on its own audio track, lines one after another in script order with a short natural pause (about 0.3–0.6 s) between sentences, and align it to the picture the task describes. (5) Lower the music under the narration with duck_audio {clip: <music clip>, underTrack: <the narration track>} (or under: [clip ids]); keep the music bed about 0.2–0.4 volume otherwise. Verify with inspect_timeline, and report the lines placed, the total length and what the generation cost.`;

/** Captions for narration (Audio and Editor): the operation shows each line's own text timed by the take's words. */
export const VOICE_CAPTIONS = `Captions of the narration: when the user wants captions for a voiceover, place the narration first, then call edit_timeline captions_from_voiceover {preset?, lines?} — it shows every line's own text timed by the words the narrator spoke (digits and abbreviations stay as written). Never retype the script into apply_captions or run captions_from_transcript on narration.`;
