//! Embed the locale catalog (`locales/` at the repo root) at compile time.
//!
//! `locales/index.json` is the list of languages; each entry's `code` must
//! have a matching `locales/<code>.json`. The generated `$OUT_DIR/locales.rs`
//! exposes `LOCALE_CODES`, `INDEX_JSON` and `locale_json`, included by
//! `src/locales.rs`. Adding a language is a new JSON file plus one line in
//! `index.json` — no Rust changes, and the build fails loudly if the catalog
//! is malformed or a listed file is missing.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    tauri_build::build();

    let manifest_dir = PathBuf::from(
        env::var("CARGO_MANIFEST_DIR").expect("cargo always sets CARGO_MANIFEST_DIR"),
    );
    let locales_dir = manifest_dir
        .join("..")
        .join("..")
        .join("..")
        .join("locales");
    let locales_dir = fs::canonicalize(&locales_dir)
        .unwrap_or_else(|err| panic!("i18n: cannot resolve {}: {err}", locales_dir.display()));

    let index_path = locales_dir.join("index.json");
    println!("cargo:rerun-if-changed={}", index_path.display());
    let index_src = fs::read_to_string(&index_path)
        .unwrap_or_else(|err| panic!("i18n: cannot read {}: {err}", index_path.display()));
    let entries: Vec<serde_json::Value> = serde_json::from_str(&index_src)
        .unwrap_or_else(|err| panic!("i18n: {} is malformed: {err}", index_path.display()));
    if entries.is_empty() {
        panic!("i18n: {} lists no languages", index_path.display());
    }
    let mut codes: Vec<String> = Vec::with_capacity(entries.len());
    for entry in &entries {
        match entry.get("code").and_then(|code| code.as_str()) {
            Some(code) if is_locale_code(code) => codes.push(code.to_string()),
            _ => panic!(
                "i18n: {} has an entry without a \"code\" string: {entry}",
                index_path.display()
            ),
        }
    }

    let mut out = String::from("// Generated by build.rs from locales/index.json — do not edit.\n");
    let list = codes
        .iter()
        .map(|code| format!("{code:?}"))
        .collect::<Vec<_>>()
        .join(", ");
    out.push_str(&format!("pub const LOCALE_CODES: &[&str] = &[{list}];\n"));
    out.push_str(&format!(
        "pub const INDEX_JSON: &str = include_str!({:?});\n",
        index_path.to_string_lossy()
    ));
    out.push_str("pub fn locale_json(code: &str) -> Option<&'static str> {\n    match code {\n");
    for code in &codes {
        let path = locales_dir.join(format!("{code}.json"));
        println!("cargo:rerun-if-changed={}", path.display());
        if !path.is_file() {
            panic!(
                "i18n: locales/index.json lists {code:?} but {} is missing",
                path.display()
            );
        }
        let src = fs::read_to_string(&path)
            .unwrap_or_else(|err| panic!("i18n: cannot read {}: {err}", path.display()));
        if serde_json::from_str::<serde_json::Value>(&src).is_err() {
            panic!("i18n: {} is malformed", path.display());
        }
        out.push_str(&format!(
            "        {code:?} => Some(include_str!({:?})),\n",
            path.to_string_lossy()
        ));
    }
    out.push_str("        _ => None,\n    }\n}\n");

    let generated =
        PathBuf::from(env::var("OUT_DIR").expect("cargo always sets OUT_DIR")).join("locales.rs");
    fs::write(&generated, out)
        .unwrap_or_else(|err| panic!("i18n: cannot write {}: {err}", generated.display()));
}

/// What a `code` from `locales/index.json` may look like: a plain file stem.
fn is_locale_code(code: &str) -> bool {
    !code.is_empty() && code.bytes().all(|b| b.is_ascii_alphanumeric() || b == b'-' || b == b'_')
}
